'use client';

import { motion } from 'framer-motion';
import { FileText, Scale, UserCheck, ShieldCheck, AlertCircle, Ban, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import SharedNavbar from '@/components/SharedNavbar';

export default function TermsOfService() {
  const [isDark, setIsDark] = useState(false);

  const sections = [
    {
      icon: UserCheck,
      title: 'Acceptance of Terms',
      gradient: 'from-blue-500 to-cyan-500',
      content: [
        {
          subtitle: 'Agreement to Terms',
          text: 'By accessing or using PadhaKU ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform.'
        },
        {
          subtitle: 'Age Requirements',
          text: 'Users must be at least 13 years old to create an account. Users under 13 require parental or guardian consent. Users between 13-18 should review these terms with a parent or guardian.'
        },
        {
          subtitle: 'Account Responsibility',
          text: 'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately of any unauthorized access.'
        }
      ]
    },
    {
      icon: ShieldCheck,
      title: 'Platform Usage & Conduct',
      gradient: 'from-purple-500 to-pink-500',
      content: [
        {
          subtitle: 'Permitted Use',
          text: 'PadhaKU is provided for educational purposes. You may use the platform to learn, create courses, take quizzes, interact with AI tools, and participate in gamification features.'
        },
        {
          subtitle: 'Prohibited Activities',
          text: 'You may NOT: (1) Share your account credentials, (2) Use automated bots or scripts to manipulate points/leaderboards, (3) Upload malicious content or viruses, (4) Harass, abuse, or harm other users, (5) Attempt to hack, reverse-engineer, or exploit the platform, (6) Use the platform for illegal activities or to violate others\' rights.'
        },
        {
          subtitle: 'Content Standards',
          text: 'User-generated content (profile information, course materials) must be respectful, lawful, and appropriate for an educational environment. We reserve the right to remove content that violates these standards.'
        },
        {
          subtitle: 'AI-Generated Content Disclaimer',
          text: 'Content generated by AI (courses, quizzes, explanations) is provided for educational purposes and may contain errors. We do not guarantee 100% accuracy. Users should verify critical information from authoritative sources.'
        }
      ]
    },
    {
      icon: Scale,
      title: 'Intellectual Property Rights',
      gradient: 'from-emerald-500 to-teal-500',
      content: [
        {
          subtitle: 'Platform Ownership',
          text: 'PadhaKU, including its design, code, features, logos, and branding, is owned by PadhaKU and protected by copyright, trademark, and other intellectual property laws.'
        },
        {
          subtitle: 'User Content License',
          text: 'By uploading content (images, text, course materials), you grant PadhaKU a non-exclusive, worldwide, royalty-free license to use, display, and distribute your content solely for platform functionality (e.g., AI analysis, course generation).'
        },
        {
          subtitle: 'Third-Party Content',
          text: 'YouTube videos, images, and other third-party content embedded on PadhaKU are owned by their respective owners. We do not claim ownership of third-party content and use it under applicable licenses and fair use provisions.'
        },
        {
          subtitle: 'AI Model Usage',
          text: 'We use third-party AI services (Google Gemini, MediaPipe, Vapi) which have their own terms of service. By using AI features, you agree to comply with those third-party terms.'
        }
      ]
    },
    {
      icon: AlertCircle,
      title: 'Disclaimers & Limitations',
      gradient: 'from-orange-500 to-amber-500',
      content: [
        {
          subtitle: 'No Warranty',
          text: 'PadhaKU is provided "AS IS" without warranties of any kind. We do not guarantee uninterrupted, error-free, or secure operation. Educational content may contain inaccuracies.'
        },
        {
          subtitle: 'Educational Use Only',
          text: 'PadhaKU is designed for supplemental learning and should not replace formal education, professional advice, or certified instruction. We are not liable for educational outcomes or decisions based on platform content.'
        },
        {
          subtitle: 'Third-Party Services',
          text: 'We integrate with Google Classroom, YouTube, and AI services. We are not responsible for the availability, accuracy, or policies of these third-party services.'
        },
        {
          subtitle: 'Limitation of Liability',
          text: 'To the maximum extent permitted by law, PadhaKU and its team shall not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of the platform, including data loss, academic consequences, or missed opportunities.'
        },
        {
          subtitle: 'Maximum Liability Cap',
          text: 'In no event shall our total liability exceed the amount you paid to PadhaKU (if any) in the 12 months preceding the claim. Since PadhaKU is currently free, this liability is $0.'
        }
      ]
    },
    {
      icon: Ban,
      title: 'Account Termination & Suspension',
      gradient: 'from-rose-500 to-pink-500',
      content: [
        {
          subtitle: 'Termination by User',
          text: 'You may delete your account at any time through your account settings or by contacting support@padhaku.com. Upon deletion, your data will be permanently removed within 30 days (subject to legal retention requirements).'
        },
        {
          subtitle: 'Termination by PadhaKU',
          text: 'We reserve the right to suspend or terminate your account immediately, without notice, if you: (1) Violate these Terms of Service, (2) Engage in fraudulent or illegal activity, (3) Abuse the platform or harm other users, (4) Fail to comply with our policies.'
        },
        {
          subtitle: 'Effect of Termination',
          text: 'Upon termination, your access to the platform will cease, and your data (courses, progress, points) will be deleted. You will lose all accumulated points, achievements, and course progress. Termination does not affect sections of these Terms that by their nature should survive (e.g., intellectual property, disclaimers, dispute resolution).'
        }
      ]
    },
    {
      icon: FileText,
      title: 'Additional Terms',
      gradient: 'from-indigo-500 to-purple-500',
      content: [
        {
          subtitle: 'Privacy Policy',
          text: 'Your use of PadhaKU is also governed by our Privacy Policy, which explains how we collect, use, and protect your data. Please review it at /privacy.'
        },
        {
          subtitle: 'Modifications to Terms',
          text: 'We may update these Terms of Service at any time. Material changes will be notified via email or platform announcement. Continued use after changes constitutes acceptance of the updated terms.'
        },
        {
          subtitle: 'Governing Law',
          text: 'These Terms are governed by the laws of India. Any disputes will be resolved through arbitration in Mumbai, Maharashtra, in accordance with Indian Arbitration and Conciliation Act, 1996.'
        },
        {
          subtitle: 'Severability',
          text: 'If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions will remain in full force and effect.'
        },
        {
          subtitle: 'No Waiver',
          text: 'Our failure to enforce any right or provision of these Terms does not constitute a waiver of that right or provision.'
        },
        {
          subtitle: 'Contact for Legal Notices',
          text: 'All legal notices, requests, or inquiries should be sent to: legal@padhaku.com. We will respond within 7 business days.'
        }
      ]
    }
  ];

  return (
    <div className={`min-h-screen ${isDark ? 'dark bg-gray-950' : 'bg-gray-50'}`}>
      {/* SHARED NAVBAR */}
      <SharedNavbar 
        isDark={isDark}
        setIsDark={setIsDark}
        activeSection="terms"
        showNavItems={true}
      />

      {/* Animated Background */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <motion.div
          className="absolute w-[600px] h-[600px] rounded-full blur-[120px]"
          style={{
            background: 'radial-gradient(circle, rgba(56, 123, 255, 0.1) 0%, transparent 70%)',
            top: '-10%',
            right: '-5%',
          }}
          animate={{
            x: [0, -50, 0],
            y: [0, 30, 0],
          }}
          transition={{
            duration: 20,
            repeat: Infinity,
            ease: "easeInOut"
          }}
        />
        <motion.div
          className="absolute w-[500px] h-[500px] rounded-full blur-[100px]"
          style={{
            background: 'radial-gradient(circle, rgba(92, 86, 255, 0.08) 0%, transparent 70%)',
            bottom: '-10%',
            left: '-5%',
          }}
          animate={{
            x: [0, 40, 0],
            y: [0, -30, 0],
          }}
          transition={{
            duration: 25,
            repeat: Infinity,
            ease: "easeInOut"
          }}
        />

        {/* Grid Pattern */}
        <div className="absolute inset-0 opacity-[0.05]">
          <svg className="w-full h-full" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <pattern id="terms-grid" width="60" height="60" patternUnits="userSpaceOnUse">
                <path d="M 60 0 L 0 0 0 60" fill="none" stroke="rgba(56, 123, 255, 0.3)" strokeWidth="1"/>
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#terms-grid)" />
          </svg>
        </div>
      </div>

      {/* Header */}
      <div className="relative pt-40 pb-32 px-8 bg-gradient-to-r from-[#0a2463] via-[#2563eb] to-[#4a4ab0] overflow-hidden">
        <div className="absolute inset-0 bg-black/20"></div>
        
        <div className="max-w-4xl mx-auto relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center"
          >
            <div className="inline-flex items-center gap-3 px-5 py-2.5 rounded-full bg-white/20 backdrop-blur-sm border border-white/30 mb-6">
              <FileText className="w-5 h-5 text-cyan-300" />
              <span className="text-white font-semibold">Terms of Service</span>
            </div>
            
            <h1 className="text-5xl lg:text-6xl font-black text-white mb-4">
              Terms & Conditions
            </h1>
            
            <p className="text-lg text-white/80 max-w-2xl mx-auto">
              Please read these terms carefully before using PadhaKU. By creating an account or using our platform, you agree to these terms.
            </p>
            
            <div className="mt-6 text-sm text-white/60">
              Last Updated: December 6, 2025
            </div>
          </motion.div>
        </div>
      </div>

      {/* Content Sections */}
      <div className="relative py-16 px-8">
        <div className="max-w-4xl mx-auto space-y-12">
          {sections.map((section, idx) => (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: idx * 0.1 }}
            >
              <div className="backdrop-blur-xl bg-white/70 dark:bg-gray-900/70 rounded-3xl border border-gray-200/50 dark:border-gray-700/50 shadow-xl p-8">
                {/* Section Header */}
                <div className="flex items-center gap-4 mb-6">
                  <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${section.gradient} p-3.5 shadow-lg`}>
                    <section.icon className="w-full h-full text-white" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
                    {section.title}
                  </h2>
                </div>

                {/* Section Content */}
                <div className="space-y-6">
                  {section.content.map((item, itemIdx) => (
                    <div key={itemIdx} className="pl-4 border-l-2 border-gray-200 dark:border-gray-700">
                      <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-2">
                        {item.subtitle}
                      </h3>
                      <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
                        {item.text}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          ))}

          {/* Contact Section */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="backdrop-blur-xl bg-gradient-to-br from-blue-50/80 to-cyan-50/80 dark:from-blue-900/30 dark:to-cyan-900/30 rounded-3xl border border-blue-200/50 dark:border-blue-700/50 shadow-xl p-8 text-center"
          >
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              Questions About These Terms?
            </h2>
            <p className="text-gray-600 dark:text-gray-400 mb-6">
              If you have any questions or need clarification about these Terms of Service, please contact us:
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center flex-wrap">
              <div className="px-6 py-3 rounded-full bg-white/60 dark:bg-gray-800/60 border border-gray-200 dark:border-gray-700">
                <span className="text-sm font-semibold text-gray-900 dark:text-white">
                  General: support@padhaku.com
                </span>
              </div>
              <div className="px-6 py-3 rounded-full bg-white/60 dark:bg-gray-800/60 border border-gray-200 dark:border-gray-700">
                <span className="text-sm font-semibold text-gray-900 dark:text-white">
                  Legal: legal@padhaku.com
                </span>
              </div>
            </div>
          </motion.div>

          {/* Acknowledgment */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="backdrop-blur-xl bg-white/60 dark:bg-gray-900/60 rounded-2xl border border-gray-200/50 dark:border-gray-700/50 p-6"
          >
            <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-3">
              Acknowledgment
            </h3>
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              By using PadhaKU, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service and our Privacy Policy. 
              If you do not agree to these terms, you must immediately cease using the platform and delete your account.
            </p>
          </motion.div>
        </div>
      </div>

      {/* Footer */}
      <footer className="relative py-8 px-8 border-t border-gray-200 dark:border-gray-800">
        <div className="max-w-4xl mx-auto text-center">
          <p className="text-sm text-gray-600 dark:text-gray-400">
            © 2025 PadhaKU - Learning, Reimagined for Everyone. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
